### ISSUE TITLE
java.lang.IncompatibleClassChangeError thrown on collection.empty

### ISSUE THREAD

**Issue by BertRobben** [mvel/mvel#200]
When running with java8 and mvel 2.4.1.Final I get a very reproducible IncompatibleClassChangeError when evaluating a trivial expression to check if an arraylist is empty. See exact unit test below.

If I run with 2.4.0.Final it still works fine. I suspect the upgrade to ASM 7 (done in 2.4.1.Final) has something to do with this.

Please fix ;-)

public class MVELTest {

    private static final int COUNT = 10000;

    @Test
    public void evaluateCollectionExpression() {
        Serializable compiled = MVEL.compileExpression("validationIssues.empty");
        Map<String, Object> properties = new HashMap<>();
        properties.put("validationIssues", new ArrayList<>());
        int trueCount = 0;
        for (int i = 0; i < COUNT; i++) {
            if (MVEL.executeExpression(compiled, properties, Boolean.class)) {
                trueCount++;
            }
        }
        System.out.println("Evaluated " + COUNT + " true -> " + trueCount);
    }
}

**Comment by MalcolmOdd** [comment]
Interestingly, if you replace .empty with .isEmpty() in the expression, it works. 
Some logic in ASMAccessorOptimizer.getMethod() is missing from ASMAccessorOptimizer.getBeanProperty() - which is called for "empty". 
The declaring class for the isEmpty method is java.lang.Collection, an interface, so it should be invoked using INVOKEINTERFACE rather than INVOKEVIRTUAL (around line 1119 in ASMAccessorOptimizer). Changing this fixes the issue.
The code seems to foresee this case by catching IllegalAccessException but this isn't thrown at this time.

**Comment by MalcolmOdd** [comment]
@mariofusco could you approve PR 201 please?
